In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [27]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [28]:
df.shape

(569, 33)

In [30]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [31]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [32]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
127,19.000,18.91,123.40,1138.0,0.08217,0.08028,0.09271,0.05627,0.1946,0.05044,...,22.320,25.73,148.20,1538.0,0.1021,0.2264,0.32070,0.12180,0.2841,0.06541
322,12.860,13.32,82.82,504.8,0.11340,0.08834,0.03800,0.03400,0.1543,0.06476,...,14.040,21.08,92.80,599.5,0.1547,0.2231,0.17910,0.11550,0.2382,0.08553
104,10.490,19.29,67.41,336.1,0.09989,0.08578,0.02995,0.01201,0.2217,0.06481,...,11.540,23.31,74.22,402.8,0.1219,0.1486,0.07987,0.03203,0.2826,0.07552
71,8.888,14.64,58.79,244.0,0.09783,0.15310,0.08606,0.02872,0.1902,0.08980,...,9.733,15.67,62.56,284.4,0.1207,0.2436,0.14340,0.04786,0.2254,0.10840
286,11.940,20.76,77.87,441.0,0.08605,0.10110,0.06574,0.03791,0.1588,0.06766,...,13.240,27.29,92.20,546.1,0.1116,0.2813,0.23650,0.11550,0.2465,0.09981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,12.680,23.84,82.69,499.0,0.11220,0.12620,0.11280,0.06873,0.1905,0.06590,...,17.090,33.47,111.80,888.3,0.1851,0.4061,0.40240,0.17160,0.3383,0.10310
459,9.755,28.20,61.68,290.9,0.07984,0.04626,0.01541,0.01043,0.1621,0.05952,...,10.670,36.92,68.03,349.9,0.1110,0.1109,0.07190,0.04866,0.2321,0.07211
529,12.070,13.44,77.83,445.2,0.11000,0.09009,0.03781,0.02798,0.1657,0.06608,...,13.450,15.77,86.92,549.9,0.1521,0.1632,0.16220,0.07393,0.2781,0.08052
481,13.900,19.24,88.73,602.9,0.07991,0.05326,0.02995,0.02070,0.1579,0.05594,...,16.410,26.42,104.40,830.5,0.1064,0.1415,0.16730,0.08150,0.2356,0.07603
164,23.270,22.04,152.10,1686.0,0.08439,0.11450,0.13240,0.09702,0.1801,0.05553,...,28.010,28.22,184.20,2403.0,0.1228,0.3583,0.39480,0.23460,0.3589,0.09187

In [33]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [34]:
y_train

127    M
322    B
104    B
71     B
286    B
      ..
64     M
459    B
529    B
481    B
164    M
Name: diagnosis, Length: 455, dtype: object

In [35]:
le = LabelEncoder()

In [36]:
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [37]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1])

In [38]:
# Numpy arrays to pytorch Tensors

In [39]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [41]:
X_train_tensor

tensor([[ 1.3605, -0.1117,  1.2781,  ...,  0.1113, -0.0798, -1.0014],
        [-0.3753, -1.4216, -0.3905,  ...,  0.0148, -0.8149,  0.1110],
        [-1.0453, -0.0227, -1.0241,  ..., -1.2628, -0.1038, -0.4425],
        ...,
        [-0.5986, -1.3935, -0.5956,  ..., -0.6214, -0.1759, -0.1660],
        [-0.0813, -0.0344, -0.1474,  ..., -0.5056, -0.8565, -0.4143],
        [ 2.5676,  0.6217,  2.4582,  ...,  1.8378,  1.1182,  0.4615]],
       dtype=torch.float64)

In [42]:
# Defining the model

In [80]:
class MySimpleNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1 ,1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights)+ self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def lossCalc(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    loss = -(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()
    return loss

In [81]:
# Defining Parameters
lr = 0.1
epochs = 30

Training pipeline

In [85]:
model = MySimpleNN(X_train_tensor)
for epoch in range(epochs):
  # Forward Pass
  y_pred = model.forward(X_train_tensor)
  # loss Calculate
  loss = model.lossCalc(y_pred,y_train_tensor)
  # Backward Pass
  loss.backward()
  # parameter update
  with torch.no_grad():
      model.weights -= lr*model.weights.grad
      model.bias -= lr*model.bias.grad
  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()
  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.8541623327933325
Epoch: 2, Loss: 3.7297083393331762
Epoch: 3, Loss: 3.603239300331857
Epoch: 4, Loss: 3.4729594135028314
Epoch: 5, Loss: 3.3354559972331197
Epoch: 6, Loss: 3.1953703352283362
Epoch: 7, Loss: 3.050654294664124
Epoch: 8, Loss: 2.902438347643235
Epoch: 9, Loss: 2.743728045621749
Epoch: 10, Loss: 2.5809896872648
Epoch: 11, Loss: 2.414757872536315
Epoch: 12, Loss: 2.2496050341014624
Epoch: 13, Loss: 2.0854246694874954
Epoch: 14, Loss: 1.9177072655491259
Epoch: 15, Loss: 1.758667810927044
Epoch: 16, Loss: 1.609675308503688
Epoch: 17, Loss: 1.46971103640395
Epoch: 18, Loss: 1.3403185205760768
Epoch: 19, Loss: 1.2258057804859843
Epoch: 20, Loss: 1.1272609069493391
Epoch: 21, Loss: 1.0452141921282387
Epoch: 22, Loss: 0.9793750186601207
Epoch: 23, Loss: 0.9284424717009732
Epoch: 24, Loss: 0.8901769508261727
Epoch: 25, Loss: 0.861811981886365
Epoch: 26, Loss: 0.8406240190892567
Epoch: 27, Loss: 0.8243561670522483
Epoch: 28, Loss: 0.8113588102436476
Epoch: 29, Loss: 0.8005246207474233
Epoch: 30, Loss: 0.791149867284254

In [86]:
model.bias

tensor([[-0.1729]], dtype=torch.float64, requires_grad=True)

In [87]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred>0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5369344353675842