In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [6]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
216,11.890,18.35,77.32,432.2,0.09363,0.11540,0.066360,0.031420,0.1967,0.06314,...,13.250,27.10,86.20,531.2,0.14050,0.30460,0.28060,0.11380,0.3397,0.08365
377,13.460,28.21,85.89,562.1,0.07517,0.04726,0.012710,0.011170,0.1421,0.05763,...,14.690,35.63,97.11,680.6,0.11080,0.14570,0.07934,0.05781,0.2694,0.07061
253,17.300,17.08,113.00,928.2,0.10080,0.10410,0.126600,0.083530,0.1813,0.05613,...,19.850,25.09,130.90,1222.0,0.14160,0.24050,0.33780,0.18570,0.3138,0.08113
393,21.610,22.28,144.40,1407.0,0.11670,0.20870,0.281000,0.156200,0.2162,0.06606,...,26.230,28.74,172.00,2081.0,0.15020,0.57170,0.70530,0.24220,0.3828,0.10070
174,10.660,15.15,67.49,349.6,0.08792,0.04302,0.000000,0.000000,0.1928,0.05975,...,11.540,19.20,73.20,408.3,0.10760,0.06791,0.00000,0.00000,0.2710,0.06164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,15.660,23.20,110.20,773.5,0.11090,0.31140,0.317600,0.137700,0.2495,0.08104,...,19.850,31.64,143.70,1226.0,0.15040,0.51720,0.61810,0.24620,0.3277,0.10190
56,19.210,18.57,125.50,1152.0,0.10530,0.12670,0.132300,0.089940,0.1917,0.05961,...,26.140,28.14,170.10,2145.0,0.16240,0.35110,0.38790,0.20910,0.3537,0.08294
296,10.910,12.35,69.14,363.7,0.08518,0.04721,0.012360,0.013690,0.1449,0.06031,...,11.370,14.82,72.42,392.2,0.09312,0.07506,0.02884,0.03194,0.2143,0.06643
114,8.726,15.83,55.84,230.9,0.11500,0.08201,0.041320,0.019240,0.1649,0.07633,...,9.628,19.62,64.48,284.4,0.17240,0.23640,0.24560,0.10500,0.2926,0.10170
308,13.500,12.71,85.69,566.2,0.07376,0.03614,0.002758,0.004419,0.1365,0.05335,...,14.970,16.94,95.48,698.7,0.09023,0.05836,0.01379,0.02210,0.2267,0.06192

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
y_train

216    B
377    B
253    M
393    M
174    B
      ..
258    M
56     M
296    B
114    B
308    B
Name: diagnosis, Length: 455, dtype: object

In [9]:
le = LabelEncoder()

In [10]:
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [11]:
y_train

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0])

In [ ]:
# Numpy arrays to pytorch Tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor

tensor([[-0.6413, -0.2252, -0.6098,  ..., -0.0274,  0.7972, -0.0039],
        [-0.1941,  2.0442, -0.2554,  ..., -0.8728, -0.3473, -0.7628],
        [ 0.8998, -0.5175,  0.8656,  ...,  1.0582,  0.3756, -0.1505],
        ...,
        [-0.9205, -1.6061, -0.9480,  ..., -1.2634, -1.2444, -1.0060],
        [-1.5426, -0.8052, -1.4979,  ..., -0.1603,  0.0304,  1.0466],
        [-0.1827, -1.5233, -0.2637,  ..., -1.4119, -1.0425, -1.2685]],
       dtype=torch.float64)

In [ ]:
# Defining the model

In [27]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

In [28]:
import torch.nn as nn
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,1),
        nn.Sigmoid()
    )
  def forward(self,X):
    out = self.network(X)
    return out

In [29]:
loss_func = nn.BCELoss()

In [30]:
# Defining Parameters
lr = 0.1
epochs = 30

Training pipeline

In [31]:
model = MySimpleNN(X_train_tensor.shape[1])
loss_func = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(),lr)
for epoch in range(epochs):
  # Forward Pass
  y_pred = model(X_train_tensor)
  # loss Calculate
  loss = loss_func(y_pred,y_train_tensor.view(-1,1))
  #zero gradients
  optimizer.zero_grad()
  # Backward Pass
  loss.backward()
  # parameter update
  optimizer.step()


  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6612576842308044
Epoch: 2, Loss: 0.5243347883224487
Epoch: 3, Loss: 0.44694527983665466
Epoch: 4, Loss: 0.396416038274765
Epoch: 5, Loss: 0.36021777987480164
Epoch: 6, Loss: 0.33265063166618347
Epoch: 7, Loss: 0.3107403516769409
Epoch: 8, Loss: 0.2927733361721039
Epoch: 9, Loss: 0.2776861786842346
Epoch: 10, Loss: 0.26478010416030884
Epoch: 11, Loss: 0.253574401140213
Epoch: 12, Loss: 0.2437260001897812
Epoch: 13, Loss: 0.23498237133026123
Epoch: 14, Loss: 0.2271527796983719
Epoch: 15, Loss: 0.22009004652500153
Epoch: 16, Loss: 0.21367834508419037
Epoch: 17, Loss: 0.2078252136707306
Epoch: 18, Loss: 0.20245561003684998
Epoch: 19, Loss: 0.19750793278217316
Epoch: 20, Loss: 0.19293120503425598
Epoch: 21, Loss: 0.18868251144886017
Epoch: 22, Loss: 0.18472568690776825
Epoch: 23, Loss: 0.18102984130382538
Epoch: 24, Loss: 0.17756852507591248
Epoch: 25, Loss: 0.1743188500404358
Epoch: 26, Loss: 0.17126090824604034
Epoch: 27, Loss: 0.16837731003761292
Epoch: 28, Loss: 0.165652796626091
Epoch: 29, Loss: 0.1630738526582718
Epoch: 30, Loss: 0.1606285125017166

In [34]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred>0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5497075915336609